import NavbarComponent from "./navbar";
import Footer from "./footer";
import WhyUs from "./whyus";
import Banner from "./banner";
import SlideShow from "./slideshow";
import UserProfile from "./userProfile";
import HistoryBooking from "./historyBooking";
import SearcResult from "./searchResult";
import ConfirmBooking from "./confirmBooking";
export { NavbarComponent,Footer,WhyUs,Banner,SlideShow,UserProfile,HistoryBooking,SearcResult,ConfirmBooking};
